### ISSUE TITLE
Can't found ../NNPACK/build/src/x86_64-fma/2d-fourier-16x16.py.o

### ISSUE THREAD

**Issue by smallworld-network-wupeng** [omair18/darknet-nnpack-cpp#1]
When I make can't found ../NNPACK/build/src/x86_64-fma/2d-fourier-16x16.py.o 
I checked ,these is not x84_64-fma directory

**Comment by omair18** [comment]
@smallworld-network-wupeng you can safely remove all such unrelated *.o files from Cmake. I hard coded the object files but couldn't get time to remove them from project.
